---
name: Report an issue
description:
  Tell us about something that is not working the way we (probably) intend
body:
  - type: markdown
    attributes:
      value: >
        There are two sections "Why?" and either "How?" or "What?".


        "Why?" means "why does something have to be done? What is the purpose of the proposed work?".

        "How?" lists a **checklist** of clearly defined items that you think need to be done to fulfill the purpose of the work.
        These checklists are to consist of clear instructions for each of which anyone can trivially check if the step was done or not.
        In other words, they have to each include or clearly imply an acceptance criterion.

        "What?" lists a **checklist** of clearly defined items that you think need to be figured out to fulfill the puprose of the work.

  - type: textarea
    id: why
    attributes:
      label: Why does it have to be done?
      description: What is the purpose of the proposed work?
    validations:
      required: true

  - type: textarea
    id: how
    attributes:
      label: How do you think does it have to be done?
      description: If you know how to do it, include "how", otherwise - "what".
      placeholder: >
         - [ ]
    validations:
      required: false

  - type: textarea
    id: what
    attributes: 
      label: What do you think needs to be figured out for it to be done?
      description: If you know how to do it, include "how", otherwise - "what".
      placeholder: >
         - [ ]
    validations:
      required: false
